[package]
name = "diem-crypto"
version = "0.0.3"
authors = ["Diem Association <opensource@diem.com>"]
publish = false
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow.workspace = true
bytes.workspace = true
curve25519-dalek.workspace = true
digest.workspace = true
ed25519-dalek.workspace = true
hex.workspace = true
hkdf.workspace = true
once_cell.workspace = true
mirai-annotations.workspace = true
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
rand.workspace = true
serde.workspace = true
serde_bytes.workspace = true
serde-name.workspace = true
sha2.workspace = true
static_assertions.workspace = true
thiserror.workspace = true
tiny-keccak.workspace = true
x25519-dalek.workspace = true
aes-gcm.workspace = true
diem-crypto-derive.workspace = true

bcs.workspace = true

[dev-dependencies]
bitvec.workspace = true
byteorder.workspace = true
proptest.workspace = true
proptest-derive.workspace = true
ripemd160.workspace = true
criterion.workspace = true
sha3.workspace = true
serde_json.workspace = true
# TODO: some tests will fail if this is set to 1.0.63
trybuild = "=1.0.53"

[features]
default = []
cloneable-private-keys = []
fuzzing = ["proptest", "proptest-derive", "cloneable-private-keys"]

[[bench]]
name = "noise"
harness = false

[[bench]]
name = "ed25519"
harness = false
