[package]
name = "df-cli"
version = "0.1.0"
description = "CLI frontend for the Move compiler and VM (with Diem Framework)"
authors = ["Diem Association <opensource@diem.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
clap.workspace = true

move-stdlib.workspace = true
move-core-types.workspace = true
move-cli.workspace = true
move-vm-test-utils.workspace = true

diem-framework-natives.workspace = true

[dev-dependencies]
datatest-stable.workspace = true
