[package]
name = "diem-framework-natives"
version = "0.0.0"
authors = ["Diem Association <opensource@diem.com>"]
publish = false
edition = "2021"
license = "Apache-2.0"

[dependencies]
move-binary-format.workspace = true
move-core-types.workspace = true
move-vm-types.workspace = true
move-vm-runtime.workspace = true

diem-crypto.workspace = true

smallvec.workspace = true
